data:
  data_provider: protein_embedding[dataset_name=casf2016-blind-docking100-hetero.polar.polar.pyg]
  data_root: /scratch/sx801/data/im_datasets
  pre_computed:
    prot_embedding_root:
    - /CASF-2016-cyang/polar.esm2_t33_650M_UR50D
record_name:
- sample_id
- file_handle
short_name: casf2016-blind-docking
training:
  valid_batch_size: 32
