data:
  data_provider: protein_embedding[dataset_name=casf-screening.hetero.polar.polar.implicit.min_dist/*.pyg]
  data_root: /scratch/sx801/data/im_datasets
  pre_computed:
    atom_prop_ds: CASF2016_screening_ligmolprop_frag20sol_012_ens.allh/????.pyg
    lig_identifier_dst: ligand_file
    lig_identifier_src: ligand_file
    prot_embedding_root:
    - /CASF-2016-cyang/polar.esm2_t33_650M_UR50D
    prot_info_ds: casf-scoring.hetero.complete.polar.polar.implicit.min_dist.pyg
    rmsd_csv: /vast/sx801/geometries/PL_physics_infusion/CASF-2016-cyang/info/casf-screening-rmsd/casf.screening.????.rmsd.csv
record_name:
- sample_id
- ligand_file
short_name: casf2016-screening
training:
  valid_batch_size: 32
