data:
  data_provider: protein_embedding[dataset_name=LIT-PCBA-D021-D022-KAT2A.polar.polar.implicit.mindist/part_*.pyg]
  data_root: /scratch/sx801/data/im_datasets
  pre_computed:
    prot_embedding_root:
    - /vast/sx801/geometries/LIT-PCBA-DiffDock/KAT2A/prot_polar.esm2_t33_650M_UR50D
record_name:
- sample_id
- file_handle
- rank
- confidence
short_name: kat2a-diffdock
